config/routes.rb
Teste::Application.routes.draw do

  

 

  resources :videos

  resources :lectures

  devise_for :clients
  
  get "carts/checkout", to:"carts#checkout"
  
  get "checkout/:id", to: "line_items#checkout", as: "checkout"
  post "notifications", to: "notifications#create", as: "notifications"
  get "processing", to: "line_items#processing", as: "processing"
  
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"
  resources :users
  resources :orders
  resources :line_items
  resources :carts

  get "store/index"
  resources :products do
    resources :lectures
    get :who_bought, on: :member
  end
  
  
  root 'store#index', as: 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  
  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
     current_item.quantity += 1
    else
     current_item = line_items.build(product_id: product_id)
    end
    current_item
  end
  
  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         
         has_many :order, dependent: :destroy
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  mount_uploader :video, VideoUploader
  mount_uploader :img, ArquivoUploader
  

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  
  def total_price
    product.price * quantity
  end
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  
  belongs_to :client
  
  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
  
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES
  
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :lectures
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  mount_uploader :video, ArquivoUploader
  mount_uploader :image_url, ArquivoUploader

  
  def self.latest
    Product.order(:updated_at).last
  end

  private
  
  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  after_destroy :ensure_an_admin_remains

  validates :name, presence: true, uniqueness: true
  has_secure_password

private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
	@total_orders = Order.count
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  include CurrentCart
  before_action :set_cart
  
  def index
    @products = Product.order(:title)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
     attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/store/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<div class="container" >
<% @products.each_slice(4) do |product| %>
    <div class="row" id="produto_catalogo">
      <div class="col-xs-3" >
          <div class="row">
            <%if product[0].present?%>
              <div class="thumbnail" id="thumb">
                <h3><%= product[0].title %></h3>
                <%= image_tag product[0].image_url.thumb.url, :class =>"thumbnail" %>
                <p id="desc_curso"><%= product[0].description %></p>
                <%= button_to 'Add to Cart', line_items_path(product_id: product[0]), remote: true %>
                <%  if current_client.try(:admin?)%>
                  <hr>
                  <div class="row" id="editar">
                    <div class="col-xs-3"><%= link_to 'Exibir', product[0] %></div>
                    <div class="col-xs-3"><%= link_to 'Editar', edit_product_path(product[0])%></div>
                    <div class="col-xs-3"><%= link_to 'Excluir', product[0], method: :delete, data: { confirm: 'Are you sure?' } %></div>
                  </div>
                <% end %>  
              </div>
            <%end%>
          </div>      
      </div>
          
      <div class="col-xs-3">
          <div class="row">
            <%if product[1].present?%>
              <div class="thumbnail" id="thumb">
              <h3><%= product[1].title %></h3>
                <%= image_tag product[1].image_url.thumb.url, :class =>"thumbnail" %>
                <p id="desc_curso"><%= product[1].description %></p>
                <%= button_to 'Add to Cart', line_items_path(product_id: product[1]), remote: true %>
                <%  if current_client.try(:admin?)%>
                  <hr>
                  <div class="row" id="editar">
                    <div class="col-xs-3"><%= link_to 'Exibir', product[1] %></div>
                    <div class="col-xs-3"><%= link_to 'Editar', edit_product_path(product[1])%></div>
                    <div class="col-xs-3"><%= link_to 'Excluir', product[1], method: :delete, data: { confirm: 'Are you sure?' } %></div>
                  </div>
                <% end %>  
              </div>   
                
              </div>
            <%end%>
          </div>
   
          
          <div class="col-xs-3">
          <div class="row">
            <%if product[2].present?%>
              <div class="thumbnail" id="thumb">
                <h3><%= product[2].title %></h3>
                  <%= image_tag product[2].image_url.thumb.url , :class =>"thumbnail" %>
                  <p id="desc_curso"><%= product[2].description %></p>
                  <%= button_to 'Add to Cart', line_items_path(product_id: product[2]), remote: true %>
                  <%  if current_client.try(:admin?)%>
                  <hr>
                  <div class="row" id="editar">
                    <div class="col-xs-3"><%= link_to 'Lições', product_lectures_path(product[2]) %></div>
                    <div class="col-xs-3"><%= link_to 'Exibir', product[2] %></div>
                    <div class="col-xs-3"><%= link_to 'Editar', edit_product_path(product[2])%></div>
                    <div class="col-xs-3"><%= link_to 'Excluir', product[2], method: :delete, data: { confirm: 'Are you sure?' } %></div>
                  </div>
                <% end %> 
              </div>
              </div>
            <%end%>
          </div>
    
          <div class="col-xs-3">
          <div class="row">
            <%if product[3].present?%>
              <div class="thumbnail" id="thumb">
                <h3><%= product[3].title %></h3>
                <%= image_tag product[3].image_url.thumb.url, :class =>"thumbnail" %>
                <p id="desc_curso"><%= product[3].description %></p>
                <%= button_to 'Add to Cart', line_items_path(product_id: product[3]), remote: true %>
                  <%  if current_client.try(:admin?)%>
                  <hr>
                  <div class="row" id="editar">
                    <div class="col-xs-3"><%= link_to 'Exibir', product[3] %></div>
                    <div class="col-xs-3"><%= link_to 'Editar', edit_product_path(product[3])%></div>
                    <div class="col-xs-3"><%= link_to 'Excluir', product[3], method: :delete, data: { confirm: 'Are you sure?' } %></div>
                  </div>
                <% end %> 
              </div>
                 
              </div>
            <%end%>
          </div>
    </div>
<% end %>
</div>