config/routes.rb
Teste::Application.routes.draw do

  

 

  resources :videos

  resources :lectures

  devise_for :clients
  
  get "carts/checkout", to:"carts#checkout"
  
  get "checkout/:id", to: "line_items#checkout", as: "checkout"
  post "notifications", to: "notifications#create", as: "notifications"
  get "processing", to: "line_items#processing", as: "processing"
  
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"
  resources :users
  resources :orders
  resources :line_items
  resources :carts

  get "store/index"
  resources :products do
    resources :lectures
    get :who_bought, on: :member
  end
  
  
  root 'store#index', as: 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  
  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
     current_item.quantity += 1
    else
     current_item = line_items.build(product_id: product_id)
    end
    current_item
  end
  
  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         
         has_many :order, dependent: :destroy
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  mount_uploader :video, VideoUploader
  mount_uploader :img, ArquivoUploader
  

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  
  def total_price
    product.price * quantity
  end
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  
  belongs_to :client
  
  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
  
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES
  
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :lectures
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  mount_uploader :video, ArquivoUploader
  mount_uploader :image_url, ArquivoUploader

  
  def self.latest
    Product.order(:updated_at).last
  end

  private
  
  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  after_destroy :ensure_an_admin_remains

  validates :name, presence: true, uniqueness: true
  has_secure_password

private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
     attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/index.html.erb
<h1>Welcome ADMIN Index</h1>
It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teste</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %> 
  </head>
  <body class='<%= controller.controller_name %>'>
  
    <div id="cart">
      <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
          <%= render @cart %>
        <% end %>
      <% end %>
    </div>
    <div id="menu_admin">
      <% if session[:user_id] %>
        <ul>
          <li><%= link_to 'Orders',orders_path%></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users',users_path%></li>
        </ul>
        <%= button_to 'Logout', logout_path, method: :delete%>
      <% end %>
    </div>
    
    <%= yield %>
 
  </body>
</html>